/*******************************************************************************

 File:    seekerMainFrame.java
 Project: OpenSonATA
 Authors: The OpenSonATA code is the result of many programmers
          over many years

 Copyright 2011 The SETI Institute

 OpenSonATA is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 OpenSonATA is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with OpenSonATA.  If not, see<http://www.gnu.org/licenses/>.
 
 Implementers of this code are requested to include the caption
 "Licensed through SETI" with a link to setiQuest.org.
 
 For alternate licensing arrangements, please contact
 The SETI Institute at www.seti.org or setiquest.org. 

*******************************************************************************/

package opensonata.dataDisplays;

/*
 * seekerFrame.java
 * Created on July 3, 2001, 3:40 PM
 */

/**
 *
 */

import java.io.*;

public class seekerMainFrame extends javax.swing.JFrame {

    /** Creates new form seekerFrame */
    public seekerMainFrame() {
        initComponents();
        boolean modal = false;
        
        // prepare & tail the log files.
        // must delete them & recreate them so that the tails work properly. 
        String archiveDir = getArchiveDir();

        String systemLogFilename = archiveDir + "/templogs/sse-system-status.txt";
        tailSystemStatus = tailFileExec(systemLogFilename, jTextAreaSystemStatus);
        
        String activityLogFilename = archiveDir + "/templogs/sse-activity-log.txt";
        tailActivityLog = tailFileExec(activityLogFilename, jTextAreaActivityLog);
        
        // start up seeker
        textUiDialog = new TextUiDialog(this, modal);
        textUiDialog.show();
        
        editParametersDialog = new EditParametersDialog(this, modal, textUiDialog);
        logsDialog = new LogsDialog(this, modal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        ViewMenu = new javax.swing.JMenu();
        jMenuItemShowTextUI = new javax.swing.JMenuItem();
        jMenuItemShowLogs = new javax.swing.JMenuItem();
        jButtonEditParameters = new javax.swing.JButton();
        jButtonStartActivity = new javax.swing.JButton();
        jButtonStopActivity = new javax.swing.JButton();
        jPanelSystemStatus = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSystemStatus = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanelActivityLog = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaActivityLog = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        
        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 12));
        FileMenu.setText("File");
        FileMenu.setFont(new java.awt.Font("Dialog", 1, 14));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        
        FileMenu.add(jMenuItemExit);
        jMenuBar1.add(FileMenu);
        ViewMenu.setText("View");
        ViewMenu.setFont(new java.awt.Font("Dialog", 1, 14));
        jMenuItemShowTextUI.setText("TextUI ...");
        jMenuItemShowTextUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowTextUIActionPerformed(evt);
            }
        });
        
        ViewMenu.add(jMenuItemShowTextUI);
        jMenuItemShowLogs.setText("Logs ...");
        jMenuItemShowLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowLogsActionPerformed(evt);
            }
        });
        
        ViewMenu.add(jMenuItemShowLogs);
        jMenuBar1.add(ViewMenu);
        
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        setTitle("jseeker");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        jButtonEditParameters.setText("Edit Parameters...");
        jButtonEditParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditParametersActionPerformed(evt);
            }
        });
        
        jButtonEditParameters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEditParametersMousePressed(evt);
            }
        });
        
        getContentPane().add(jButtonEditParameters, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, 30));
        
        jButtonStartActivity.setText("Start Activity");
        jButtonStartActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startActivityButtonPressed(evt);
            }
        });
        
        getContentPane().add(jButtonStartActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 20, 135, 30));
        
        jButtonStopActivity.setText("Stop Activity");
        jButtonStopActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonStopActivityMousePressed(evt);
            }
        });
        
        getContentPane().add(jButtonStopActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 135, 30));
        
        jPanelSystemStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        jPanelSystemStatus.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(jTextAreaSystemStatus);
        
        jPanelSystemStatus.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, 715, 145));
        
        jLabel1.setText("System Status:");
        jPanelSystemStatus.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        
        getContentPane().add(jPanelSystemStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, 740, 190));
        
        jPanelActivityLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        jPanelActivityLog.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(jTextAreaActivityLog);
        
        jPanelActivityLog.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, 715, 145));
        
        jLabel2.setText("Activity Log:");
        jPanelActivityLog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        
        getContentPane().add(jPanelActivityLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 740, 190));
        
        setJMenuBar(jMenuBar1);
        pack();
    }//GEN-END:initComponents

    private void jMenuItemShowLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowLogsActionPerformed
        // Add your handling code here:
       logsDialog.show();
    }//GEN-LAST:event_jMenuItemShowLogsActionPerformed

    private void jMenuItemShowTextUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowTextUIActionPerformed
        // Add your handling code here:
        textUiDialog.show();
    }//GEN-LAST:event_jMenuItemShowTextUIActionPerformed

    private void jButtonEditParametersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditParametersMousePressed
        // Add your handling code here:
        editParametersDialog.show();
    }//GEN-LAST:event_jButtonEditParametersMousePressed

    private void jButtonStopActivityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopActivityMousePressed
        // Add your handling code here:
         textUiDialog.sendCommand("stop");
    }//GEN-LAST:event_jButtonStopActivityMousePressed

    private void startActivityButtonPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startActivityButtonPressed
        // Add your handling code here:
        textUiDialog.sendCommand("start");
    }//GEN-LAST:event_startActivityButtonPressed

    private void jButtonEditParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditParametersActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jButtonEditParametersActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    // Remove the file, recreate it, then tail it.
    // Need to remove & recreate so that the tail tracks the output correctly.
    private RunExecWrapper tailFileExec(String filename, javax.swing.JTextArea textarea)
    {
        try {
            File file = new File(filename);
            file.delete();
            file.createNewFile();
        }
        catch (IOException e)
	{ 
            System.out.println("error creating file " + filename);
	} 
        String cmd = "tail +0f " + filename;  
        return new RunExecWrapper(cmd, textarea);     
    }
 
    private String getArchiveDir()
    {
        EnvReader env = new EnvReader();
        String archiveDir = env.getEnvVar("SSE_ARCHIVE"); 
        if (archiveDir == null)
        {
            archiveDir = env.getEnvVar("HOME") + "/sonata_archive"; 
        }
        return archiveDir;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new seekerMainFrame().show();
    }

    private TextUiDialog textUiDialog;
    private EditParametersDialog editParametersDialog;
    private LogsDialog logsDialog;
    private RunExecWrapper tailSystemStatus;
    private RunExecWrapper tailActivityLog;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JMenuItem jMenuItemShowTextUI;
    private javax.swing.JMenuItem jMenuItemShowLogs;
    private javax.swing.JButton jButtonEditParameters;
    private javax.swing.JButton jButtonStartActivity;
    private javax.swing.JButton jButtonStopActivity;
    private javax.swing.JPanel jPanelSystemStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSystemStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelActivityLog;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaActivityLog;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}