#!/bin/sh

echo "libtoolize..."
libtoolize --force --automake 

echo "aclocal..."
aclocal

echo "autoheader..."
autoheader

echo "autoconf..."
autoconf --force    

echo "automake..."
automake --add-missing --force-missing  

echo "configure..."
./configure $*

